version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app
    image: app
    ports:
      - 9090:9090
    depends_on:
      - postgres

volumes:
  pg-data:
